stores:
  - domain: "sc-domain:megamix.sk"
    country: "svk"
    keywords:
      - keyword: "akusticke peny"
        volume: 110
      - keyword: "akusticka pena"
        volume: 880
      - keyword: "akusticke panely"
        volume: 2900
      - keyword: "akusticke lamely"
        volume: 320
      - keyword: "izolacna pena"
        volume: 260
      - keyword: "magnety"
        volume: 1000
      - keyword: "magnety na chladnicku"
        volume: 320
      - keyword: "neodymovy magnet"
        volume: 140
      - keyword: "magnety na tabulu"
        volume: 210
      - keyword: "sklenene flase"
        volume: 210
      - keyword: "skumavky"
        volume: 170
      - keyword: "medeny drot"
        volume: 110
      - keyword: "medeny plech"
        volume: 110
      - keyword: "medene plechy"
        volume: 20
      - keyword: "medena paska"
        volume: 170
      - keyword: "medene pasky"
        volume: 10
      - keyword: "mosadzne plechy"
        volume: 10
      - keyword: "mosadzny drot"
        volume: 20
      - keyword: "tkaniny"
        volume: 260
      - keyword: "latky"
        volume: 4400
  
  - domain: "sc-domain:megamix.shop"
    country: "cze"
    keywords:
      - keyword: "akusticke peny"
        volume: 70
      - keyword: "akusticka pena"
        volume: 720
      - keyword: "akusticke panely"
        volume: 9900
      - keyword: "izolacni pena"
        volume: 140
      - keyword: "magnety"
        volume: 2900
      - keyword: "sklenena lahev"
        volume: 1300
      - keyword: "sklenene lahve"
        volume: 260
      - keyword: "zkumavka"
        volume: 1600        
      - keyword: "zkumavky"
        volume: 590
      - keyword: "neodymové magnety"
        volume: 2400
      - keyword: "medeny drat"
        volume: 
      - keyword: "medene plech"
        volume: 480
      - keyword: "medena paska"
        volume: 260
      - keyword: "mosazny drat"
        volume: 20
      - keyword: "latky"
        volume: 5400

  - domain: "sc-domain:omegamix.hu"
    country: "hun"
    keywords:
      - keyword: "hangszigetelő panel"
        volume: 2400
      - keyword: "hangszigetelő szivacs"
        volume: 1600
      - keyword: "hangszigetelő"
        volume: 1000
      - keyword: "hangszigetelő hab"
        volume: 70
      - keyword: "hangszigetelő panelek"
        volume: 70
      - keyword: "szigetelő hab"
        volume: 140
      - keyword: "neodímium mágnes"
        volume: 1000      
      - keyword: "mágnesek"
        volume: 170
      - keyword: "pálinkás üvegek"
        volume: 1900
      - keyword: "rézdrót"
        volume: 210
      - keyword: "rézlemez"
        volume: 170
      - keyword: "rézszalag"
        volume: 110
      - keyword: "sárgaréz drót"
        volume: 30
      - keyword: "szövetek"
        volume: 880

  - domain: "sc-domain:omegamix.at"
    country: "aut"
    keywords:
      - keyword: "schallschutz"
        volume: 480
      - keyword: "schallschutzplatten"
        volume: 720
      - keyword: "lärmschutz wand"
        volume: 720
      - keyword: "schalldämmung wand"
        volume: 590
      - keyword: "akustik paneele"
        volume: 22200
      - keyword: "akustik paneel"
        volume: 880
      - keyword: "akustik panel"
        volume: 880
      - keyword: "akustik paneele wand"
        volume: 210
      - keyword: "magnete"
        volume: 1000      
      - keyword: "magnete neodym"
        volume: 1300
      - keyword: "glasflaschen"
        volume: 800
      - keyword: "reagenzgläser"
        volume: 1300
      - keyword: "kupferdraht"
        volume: 320
      - keyword: "kupferbleche"
        volume: 260
      - keyword: "kupferband"
        volume: 210
      - keyword: "messingbleche"
        volume: 110
      - keyword: "messingdraht"
        volume: 50

  - domain: "sc-domain:omegamix.nl"
    country: "nld"
    keywords:
      - keyword: "geluidsisolatie"
        volume: 
      - keyword: "akoestisch schuim"
        volume: 480
      - keyword: "akoestische panelen"
        volume: 27100
      - keyword: "akoestische platen"
        volume: 590
      - keyword: "butyl"
        volume: 320
      - keyword: "isolatiemat"
        volume: 390
      - keyword: "polyethyleen"
        volume: 1900
      - keyword: "neodymium magneet"
        volume: 1300
      - keyword: "magneten"
        volume: 4400
      - keyword: "glazen flessen"
        volume: 3600
      - keyword: "reageerbuisjes"
        volume: 1300
      - keyword: "koperdraad"
        volume: 1600
      - keyword: "koper plate"
        volume: 590
      - keyword: "kopertape"
        volume: 590
      - keyword: "messing draad"
        volume: 110

  - domain: "sc-domain:omegamix.de"
    country: "aut"
    keywords:
      - keyword: "schallschutz"
        volume: 5400
      - keyword: "schallschutzplatten"
        volume: 8100
      - keyword: "lärmschutz wand"
        volume: 3600
      - keyword: "schalldämmung wand"
        volume: 3600
      - keyword: "akustik paneele"
        volume: 201000
      - keyword: "akustik paneel"
        volume: 6600
      - keyword: "akustik panel"
        volume: 6600
      - keyword: "akustik wandpaneele"
        volume: 6600
      - keyword: "magnete"
        volume: 14800      
      - keyword: "magnete neodym"
        volume: 12100
      - keyword: "glasflaschen"
        volume: 8100
      - keyword: "reagenzgläser"
        volume: 12100
      - keyword: "kupferdraht"
        volume: 2400
      - keyword: "kupferbleche"
        volume: 2400
      - keyword: "kupferband"
        volume: 1900
      - keyword: "messingbleche"
        volume: 590
      - keyword: "messingdraht"
        volume: 390
